services:
  - type: web
    name: thuoclaohongcon
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        fromDatabase: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://thuoclaohongcon.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
    autoDeploy: true